name="fastfind"
compatibility_date="2024-04-02"

[vars]
UPSTASH_REDIS_REST_TOKEN=AacZASQgZTc3ZTZjYmQtNTAzYS00YTI3LWEwMmMtZmNkMjc2NTExMDQwYzQ4Yjc4N2E3MmQ4NDEzN2I2MzZjOGU3MGUzOWRjNzU=,
UPSTASH_REDIS_REST_URL=https://pure-earwig-42777.upstash.io